[0m23:12:03.503342 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F1836AD4F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F18359CF20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F184196240>]}


============================== 23:12:03.513341 | 87436f56-245e-4184-8775-83cdb4ca96d0 ==============================
[0m23:12:03.513341 [info ] [MainThread]: Running with dbt=1.10.5
[0m23:12:03.514341 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\monis\\.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'invocation_command': 'dbt run', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m23:12:03.516556 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\monis\OneDrive\Desktop\ecommerce_elt_project\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m23:12:03.517967 [debug] [MainThread]: Command `dbt run` failed at 23:12:03.517967 after 0.19 seconds
[0m23:12:03.517967 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F183A9BA40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F183A9BE90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F1836AD4F0>]}
[0m23:12:03.518980 [debug] [MainThread]: Flushing usage events
[0m23:12:04.875090 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m23:13:17.976459 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026485F64800>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026485F67320>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026485F64830>]}


============================== 23:13:17.981461 | 29b4386b-04d2-4704-a9ba-c56cc7ccd005 ==============================
[0m23:13:17.981461 [info ] [MainThread]: Running with dbt=1.10.5
[0m23:13:17.982461 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\monis\\.dbt', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m23:13:17.983462 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\monis\OneDrive\Desktop\ecommerce_elt_project\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m23:13:17.984462 [debug] [MainThread]: Command `dbt run` failed at 23:13:17.984462 after 0.14 seconds
[0m23:13:17.985462 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026485F8FB30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000264852306B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000264862BFD70>]}
[0m23:13:17.986462 [debug] [MainThread]: Flushing usage events
[0m23:13:19.319266 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m08:01:24.144781 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000276F1770EF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000276EF5E72C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000276F1453E30>]}


============================== 08:01:24.151779 | b4d2d5e0-983b-4b28-9cc7-9f163db89e4c ==============================
[0m08:01:24.151779 [info ] [MainThread]: Running with dbt=1.10.5
[0m08:01:24.152787 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\monis\\.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt run', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m08:01:24.152787 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\monis\OneDrive\Desktop\ecommerce_elt_project\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m08:01:24.154786 [debug] [MainThread]: Command `dbt run` failed at 08:01:24.154786 after 0.16 seconds
[0m08:01:24.154786 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000276F11A02C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000276F1C1D610>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000276F1E21190>]}
[0m08:01:24.155785 [debug] [MainThread]: Flushing usage events
[0m08:01:25.323977 [debug] [MainThread]: An error was encountered while trying to flush usage events
